/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus_android_jni_sample_NDK_Sample */

#ifndef _Included_com_example_asus_android_jni_sample_NDK_Sample
#define _Included_com_example_asus_android_jni_sample_NDK_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus_android_jni_sample_NDK_Sample
 * Method:    ndkSampleMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_asus_android_1jni_1sample_NDK_1Sample_ndkSampleMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
